# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hubsync
# "app" is the name of this project. This will also be added to your AWS resource names.
app: event-driven
# "service" is the name of this project. This will also be added to your AWS resource names.
service: event-driv-product

provider:
  name: aws
  runtime: nodejs22.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
